root=vsevolod.azovsky@gmail.com
mailhub=smtp.gmail.com:587
AuthUser=vsevolod.azovsky@gmail.com
AuthPass=XXX_no_quotes_or_spaces
AuthMethod=LOGIN
UseTLS=YES
UseSTARTTLS=YES
FromLineOverride=YES
maildomain=localhost
hostname=bbb
