#! /ban/bash

git config --global core.excludesfile ~/.gitignore

git config --global pull.rebase false

git config --global core.fileMode false
git config core.fileMode false

# ULTIMATE GIT pull
git fetch origin && git reset --hard origin/$(git branch --show-current) && git clean -fd
